inherit: true

tools:
  external_code_coverage: false
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer:
    config:
      level: "PSR2"

checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - omnipay/omnipay
      - silverstripe-australia/gridfieldextensions
      - silverstripe/silverstripe-omnipay
      - silvershop/core

filter:
  paths: [code/*, tests/*]
