---
Name: silvershop-productmodel
After: '#silvershop-config'
---
SilverShop\Page\Product:
  db:
    Model: Varchar(100)
  extensions:
    - AntonyThorpe\SilverShopProductModel\Product
SilverShop\Page\ProductCategory:
  extensions:
    - AntonyThorpe\SilverShopProductModel\ProductCategory
